# Generated by Django 5.2.6 on 2026-04-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_tipo_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_etapa', to='proyectos.faseproyecto'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_etapa', to='proyectos.faseproyecto'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_etapa', to='proyectos.faseproyecto'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_etapa', to='proyectos.faseproyecto'),
        ),
    ]
