# Generated by Django 5.2.6 on 2026-04-16 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_avance_fase_evidencia_fase_observacion_fase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('impresion_3d', 'Impresion 3D'), ('computacion', 'Computacion'), ('herramientas', 'Herramientas'), ('electronica', 'Electronica'), ('insumos', 'Insumos'), ('otros', 'Otros')], max_length=30)),
                ('categoria', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('fungible', 'Fungible'), ('no_fungible', 'No fungible')], max_length=20)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad', models.CharField(max_length=40)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(blank=True, max_length=160)),
                ('observacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'item de inventario',
                'verbose_name_plural': 'items de inventario',
                'ordering': ['area', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_inventario', to='proyectos.faseproyecto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='proyectos.iteminventario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_inventario', to='proyectos.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uso de inventario',
                'verbose_name_plural': 'usos de inventario',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
