# Generated by Django 5.2.6 on 2026-04-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_iteminventario_usoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='indicadores',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='kpi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivo_especifico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivo_principal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='resultados_esperados',
            field=models.TextField(blank=True),
        ),
    ]
