# Generated by Django 5.2.6 on 2026-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_proyecto_indicadores_proyecto_kpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='trl_inicial',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Principios básicos observados'), (2, 'Concepto tecnológico formulado'), (3, 'Prueba de concepto experimental'), (4, 'Validación en laboratorio'), (5, 'Validación en entorno relevante'), (6, 'Prototipo demostrado en entorno relevante'), (7, 'Prototipo demostrado en entorno real'), (8, 'Sistema completo y validado'), (9, 'Sistema probado con éxito en entorno real')], null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='trl_objetivo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Principios básicos observados'), (2, 'Concepto tecnológico formulado'), (3, 'Prueba de concepto experimental'), (4, 'Validación en laboratorio'), (5, 'Validación en entorno relevante'), (6, 'Prototipo demostrado en entorno relevante'), (7, 'Prototipo demostrado en entorno real'), (8, 'Sistema completo y validado'), (9, 'Sistema probado con éxito en entorno real')], null=True),
        ),
    ]
