# Generated by Django 5.2.6 on 2026-05-18 21:37

import django.db.models.deletion
from django.db import migrations, models


def crear_organizacion_inicial(apps, schema_editor):
    Organizacion = apps.get_model('proyectos', 'Organizacion')
    Usuario = apps.get_model('proyectos', 'Usuario')
    Proyecto = apps.get_model('proyectos', 'Proyecto')
    organizacion, _ = Organizacion.objects.get_or_create(
        slug='fab-inacap-puerto-montt',
        defaults={
            'nombre': 'FAB INACAP Puerto Montt',
            'color_principal': '#cf3f4f',
            'color_secundario': '#1f334d',
            'activa': True,
        },
    )
    Usuario.objects.filter(organizacion__isnull=True).update(organizacion=organizacion)
    Proyecto.objects.filter(organizacion__isnull=True).update(organizacion=organizacion)


def revertir_organizacion_inicial(apps, schema_editor):
    Usuario = apps.get_model('proyectos', 'Usuario')
    Proyecto = apps.get_model('proyectos', 'Proyecto')
    Usuario.objects.update(organizacion=None)
    Proyecto.objects.update(organizacion=None)


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_objetivoespecifico_resultadoesperado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizaciones/logos/%Y/%m/')),
                ('color_principal', models.CharField(default='#cf3f4f', max_length=7)),
                ('color_secundario', models.CharField(default='#1f334d', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='resultadoesperado',
            name='trl_objetivo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Principios básicos observados'), (2, 'Concepto tecnológico formulado'), (3, 'Prueba de concepto experimental'), (4, 'Validación en laboratorio'), (5, 'Validación en entorno relevante'), (6, 'Prototipo demostrado en entorno relevante'), (7, 'Prototipo demostrado en entorno real'), (8, 'Sistema completo y validado'), (9, 'Sistema probado con éxito en entorno real')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin_organizacion', 'Administrador de organizacion'), ('lider', 'Lider'), ('integrante', 'Integrante'), ('alumno', 'Alumno'), ('practicante', 'Practicante'), ('profesor', 'Profesor / Líder'), ('administrador', 'Administrador')], default='practicante', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.organizacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='proyectos.organizacion'),
        ),
        migrations.RunPython(crear_organizacion_inicial, revertir_organizacion_inicial),
    ]
