# Generated by Django 5.2.6 on 2026-05-19 13:22

import django.db.models.deletion
from django.db import migrations, models


AREAS_PUERTO_MONTT = [
    ("fab-puerto-montt", "FAB Puerto Montt", "fabinacappuertomontt@gmail.com", True),
    ("direccion-vida-estudiantil-dae", "Dirección de Vida Estudiantil (DAE)", "jcvenegas@inacap.cl", False),
    ("registro-curricular", "Registro Curricular", "smontiel@inacap.cl", False),
    ("apoyo-pedagogico-academico", "Apoyo Pedagógico y Académico", "c_bustos@inacap.cl", False),
    ("admision-comunicaciones", "Admisión y Comunicaciones", "rcepeda@inacap.cl", False),
    ("educacion-continua", "Educación Continua", "lroman@inacap.cl", False),
    ("biblioteca", "Biblioteca", "jumeza@inacap.cl", False),
    ("finanzas-tesoreria", "Finanzas / Tesorería", "eiturra@inacap.cl", False),
    ("soporte-informatico", "Soporte Informático", "pquilahuil@inacap.cl", False),
    ("vinculacion-medio-innovacion", "Vinculación con el Medio e Innovación", "ssantana@inacap.cl", False),
    ("turismo-hospitalidad-gastronomia", "Turismo y Hospitalidad / Gastronomía", "s_rojasg@inacap.cl", False),
    ("informatica-telecomunicaciones-diseno-digital", "Informática y Telecomunicaciones / Diseño e Industria Digital", "rvalderas@inacap.cl", False),
    ("mecanica-electromovilidad", "Mecánica / Electromovilidad", "bcardenasc@inacap.cl", False),
    ("electricidad-electronica", "Electricidad y Electrónica", "mhornig@inacap.cl", False),
    ("administracion-negocios-agricola", "Administración y Negocios / Agrícola", "vmunozv@inacap.cl", False),
    ("logistica-agricola", "Logística / Agrícola", "moyarzuns@inacap.cl", False),
    ("salud", "Salud", "ggodoye@inacap.cl", False),
]


def crear_areas_inacap_puerto_montt(apps, schema_editor):
    Organizacion = apps.get_model("proyectos", "Organizacion")
    Area = apps.get_model("proyectos", "Area")
    Usuario = apps.get_model("proyectos", "Usuario")
    Proyecto = apps.get_model("proyectos", "Proyecto")

    organizacion, _ = Organizacion.objects.get_or_create(
        slug="fab-inacap-puerto-montt",
        defaults={
            "nombre": "FAB INACAP Puerto Montt",
            "color_principal": "#cf3f4f",
            "color_secundario": "#1f334d",
            "activa": True,
        },
    )

    areas = {}
    for slug, nombre, correo, es_fab in AREAS_PUERTO_MONTT:
        area, _ = Area.objects.update_or_create(
            organizacion=organizacion,
            slug=slug,
            defaults={
                "nombre": nombre,
                "correo_contacto": correo,
                "activa": True,
                "es_fab": es_fab,
            },
        )
        areas[slug] = area

    area_fab = areas["fab-puerto-montt"]
    Usuario.objects.filter(organizacion=organizacion, area__isnull=True).update(area=area_fab)
    Usuario.objects.filter(organizacion__isnull=True).update(organizacion=organizacion, area=area_fab)
    Proyecto.objects.filter(organizacion=organizacion, area__isnull=True).update(area=area_fab)
    Proyecto.objects.filter(organizacion__isnull=True).update(organizacion=organizacion, area=area_fab)


def revertir_areas_inacap_puerto_montt(apps, schema_editor):
    Organizacion = apps.get_model("proyectos", "Organizacion")
    Area = apps.get_model("proyectos", "Area")
    Usuario = apps.get_model("proyectos", "Usuario")
    Proyecto = apps.get_model("proyectos", "Proyecto")

    try:
        organizacion = Organizacion.objects.get(slug="fab-inacap-puerto-montt")
    except Organizacion.DoesNotExist:
        return

    areas = Area.objects.filter(organizacion=organizacion, slug__in=[area[0] for area in AREAS_PUERTO_MONTT])
    Usuario.objects.filter(area__in=areas).update(area=None)
    Proyecto.objects.filter(area__in=areas).update(area=None)
    areas.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_organizacion_alter_resultadoesperado_trl_objetivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=90)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('es_fab', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='proyectos.organizacion')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.area'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='proyectos.area'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('organizacion', 'slug'), name='area_unica_por_organizacion'),
        ),
        migrations.RunPython(crear_areas_inacap_puerto_montt, revertir_areas_inacap_puerto_montt),
    ]
