# Generated by Django 5.2.6 on 2026-05-20 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def asignar_creador_inicial(apps, schema_editor):
    Proyecto = apps.get_model("proyectos", "Proyecto")
    for proyecto in Proyecto.objects.filter(creador__isnull=True).prefetch_related("responsables"):
        responsable = proyecto.responsables.order_by("id").first()
        if responsable:
            proyecto.creador = responsable
            proyecto.save(update_fields=["creador"])


def revertir_creador_inicial(apps, schema_editor):
    Proyecto = apps.get_model("proyectos", "Proyecto")
    Proyecto.objects.update(creador=None)


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_area_proyecto_area_usuario_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(asignar_creador_inicial, revertir_creador_inicial),
    ]
