# Generated by Django 5.2.6 on 2026-05-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0023_proyecto_creador"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionIAEtapa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("etapa_slug", models.SlugField(max_length=120)),
                ("etapa_nombre", models.CharField(max_length=160)),
                ("trl_actual", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("trl_sugerido", models.CharField(blank=True, max_length=40)),
                ("recomienda_avanzar", models.BooleanField(default=False)),
                ("confianza", models.CharField(blank=True, max_length=40)),
                ("justificacion", models.TextField(blank=True)),
                ("faltantes", models.JSONField(blank=True, default=list)),
                ("acciones_sugeridas", models.JSONField(blank=True, default=list)),
                ("respuesta", models.JSONField(blank=True, default=dict)),
                ("decision", models.CharField(choices=[("pendiente", "Pendiente"), ("aceptada", "Aceptada"), ("rechazada", "Rechazada")], default="pendiente", max_length=20)),
                ("motivo_decision", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("decidido_en", models.DateTimeField(blank=True, null=True)),
                ("decidido_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="revisiones_ia_decididas", to=settings.AUTH_USER_MODEL)),
                ("fase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisiones_ia", to="proyectos.faseproyecto")),
                ("proyecto", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisiones_ia", to="proyectos.proyecto")),
                ("solicitado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="revisiones_ia_solicitadas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
