# Generated by Django 5.2.6 on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0027_evidencia_tarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="dominio_correo",
            field=models.CharField(
                blank=True,
                help_text="Dominio permitido para detectar usuarios de la organización, por ejemplo inacap.cl.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="encargado",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizacion_encargada",
                to="proyectos.usuario",
            ),
        ),
    ]
