# Generated by Codex on 2026-05-28

from django.db import migrations


def asignar_encargado_inacap(apps, schema_editor):
    Organizacion = apps.get_model("proyectos", "Organizacion")
    Usuario = apps.get_model("proyectos", "Usuario")

    organizacion, _ = Organizacion.objects.get_or_create(
        slug="fab-inacap-puerto-montt",
        defaults={
            "nombre": "FAB INACAP Puerto Montt",
            "color_principal": "#cf3f4f",
            "color_secundario": "#1f334d",
            "activa": True,
        },
    )
    organizacion.nombre = "FAB INACAP Puerto Montt"
    organizacion.dominio_correo = "inacapmail.cl"
    organizacion.activa = True

    encargado = Usuario.objects.filter(email__iexact="fabinacappuertomontt@gmail.com").first()
    if encargado:
        encargado.organizacion = organizacion
        encargado.rol = "admin_organizacion"
        encargado.estado_registro = "aprobado"
        encargado.correo_verificado = True
        encargado.is_active = True
        encargado.save(
            update_fields=[
                "organizacion",
                "rol",
                "estado_registro",
                "correo_verificado",
                "is_active",
            ]
        )
        organizacion.encargado = encargado

    organizacion.save(update_fields=["nombre", "dominio_correo", "activa", "encargado"])


def revertir_encargado_inacap(apps, schema_editor):
    Organizacion = apps.get_model("proyectos", "Organizacion")
    Usuario = apps.get_model("proyectos", "Usuario")

    organizacion = Organizacion.objects.filter(slug="fab-inacap-puerto-montt").first()
    encargado = Usuario.objects.filter(email__iexact="fabinacappuertomontt@gmail.com").first()
    if organizacion and organizacion.encargado_id == getattr(encargado, "id", None):
        organizacion.encargado = None
        organizacion.save(update_fields=["encargado"])


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0028_organizacion_dominio_correo_organizacion_encargado"),
    ]

    operations = [
        migrations.RunPython(asignar_encargado_inacap, revertir_encargado_inacap),
    ]
