# Generated by Django 5.2.6 on 2026-06-04 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_renombrar_crea_inacap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='area',
            field=models.CharField(choices=[('impresion_3d', 'Impresión 3D'), ('electronica', 'Electrónica'), ('corte_laser', 'Corte láser'), ('vinilo_ploteo', 'Vinilo / ploteo'), ('carpinteria_cnc', 'Carpintería / CNC'), ('costura_textil', 'Costura / textil'), ('general', 'General / bodega')], max_length=30),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='categoria',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('limitado', 'Stock limitado'), ('reservado', 'Reservado'), ('mantenimiento', 'En mantenimiento'), ('agotado', 'Agotado')], default='disponible', max_length=30),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='tipo',
            field=models.CharField(choices=[('material', 'Material / insumo'), ('filamento', 'Filamento'), ('herramienta', 'Herramienta'), ('equipo', 'Equipo / máquina'), ('componente', 'Componente electrónico'), ('cable', 'Cable / conector'), ('otro', 'Otro'), ('fungible', 'Fungible (legacy)'), ('no_fungible', 'No fungible (legacy)')], max_length=20),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(blank=True, choices=[('compra', 'Compra'), ('donacion', 'Donación'), ('devolucion', 'Devolución'), ('ajuste', 'Ajuste de inventario'), ('produccion', 'Producción propia'), ('otro', 'Otro')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='proyectos.iteminventario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
