# Generated by Django 5.2.6 on 2026-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0032_movimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/%Y/%m/', verbose_name='Foto del proyecto'),
        ),
    ]
