# Generated by Django 5.2.6 on 2026-06-23 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0035_alter_mensajeprivado_destinatario_grupochat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('modelado', 'Modelado 3D'), ('slicer', 'Slicer / Impresión'), ('electronica', 'Electrónica / PCB'), ('diseno', 'Diseño gráfico / Vinilo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_configuracion', models.FileField(blank=True, null=True, upload_to='software_config/')),
                ('icono', models.CharField(blank=True, default='ti-app-window', help_text='Nombre de ícono Tabler, ej: ti-printer, ti-cube', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_creado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Software / Configuración',
                'verbose_name_plural': 'Software / Configuraciones',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
