# Generated by Django 5.2.6 on 2026-06-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0036_softwareconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareconfiguracion',
            name='logo',
            field=models.ImageField(blank=True, help_text='Opcional: Sube el logo oficial del programa', null=True, upload_to='software_logos/'),
        ),
        migrations.AlterField(
            model_name='softwareconfiguracion',
            name='icono',
            field=models.CharField(blank=True, default='bi-pc-display', help_text='Clase del ícono (ej. bi-printer, bi-box, bi-pc-display)', max_length=50),
        ),
    ]
