# Generated by Django 5.2.6 on 2026-06-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0038_carpetaarchivos_archivoadjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareconfiguracion',
            name='archivo_configuracion',
        ),
    ]
