# Generated by Django 5.2.6 on 2026-06-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0039_remove_softwareconfiguracion_archivo_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareconfiguracion',
            name='software_asociado',
            field=models.ForeignKey(blank=True, help_text='Opcional: Si este software es un complemento/plugin de otro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complementos', to='proyectos.softwareconfiguracion'),
        ),
    ]
