# Generated by Django 5.2.6 on 2026-06-25 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0040_softwareconfiguracion_software_asociado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareconfiguracion',
            name='software_asociado',
        ),
        migrations.AddField(
            model_name='softwareconfiguracion',
            name='proyecto_asociado',
            field=models.ForeignKey(blank=True, help_text='Opcional: Si este software se usa para un proyecto específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_configuraciones', to='proyectos.proyecto'),
        ),
    ]
