# Generated by Django 5.2.6 on 2026-07-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0041_remove_softwareconfiguracion_software_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventario',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario', to='proyectos.organizacion'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='alias_login',
            field=models.SlugField(blank=True, help_text="Atajo opcional para la URL de acceso, por ejemplo 'inacap' en vez del slug completo.", max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='softwareconfiguracion',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_configuraciones', to='proyectos.organizacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Obliga a definir una contraseña propia antes de usar la plataforma.'),
        ),
    ]
