# Generated by Django 5.2.6 on 2026-10-01 13:48

from django.db import migrations, models


def superadmin_a_administrador(apps, schema_editor):
    Usuario = apps.get_model("proyectos", "Usuario")
    Usuario.objects.filter(rol="superadmin").update(rol="administrador")


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0041_remove_softwareconfiguracion_software_asociado_and_more'),
    ]

    operations = [
        migrations.RunPython(superadmin_a_administrador, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_organizacion', 'Administrador de organizacion'), ('lider', 'Lider'), ('integrante', 'Integrante'), ('alumno', 'Alumno'), ('practicante', 'Practicante'), ('profesor', 'Profesor / Líder'), ('administrador', 'Administrador')], default='practicante', max_length=20),
        ),
    ]
