# Generated by Django 5.2.6 on 2026-07-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0043_asignar_organizacion_a_datos_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='alias_login',
            field=models.SlugField(blank=True, help_text="Atajo opcional para la URL de acceso, por ejemplo 'duoc' en vez del slug completo.", max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='dominio_correo',
            field=models.CharField(blank=True, help_text='Dominio permitido para detectar usuarios de la organización, por ejemplo empresa.cl.', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='paleta_visual',
            field=models.CharField(choices=[('clasica', 'Clasica'), ('pacifico', 'Azul pacifico'), ('bosque', 'Verde bosque'), ('cobalto', 'Cobalto'), ('coral', 'Coral profesional')], default='clasica', max_length=20),
        ),
    ]
