# Generated by Django 5.2.6 on 2026-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0045_renombrar_paleta_inacap_a_clasica'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='exige_evidencia_trl',
            field=models.BooleanField(default=False, help_text='Si se activa, un nivel TRL solo se da por alcanzado cuando existe al menos una evidencia cargada en esa etapa. El nivel deja de auto-declararse.'),
        ),
    ]
