# Generated by Django 5.2.6 on 2026-07-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0046_organizacion_exige_evidencia_trl'),
    ]

    operations = [
        migrations.AddField(
            model_name='faseproyecto',
            name='entorno_validacion',
            field=models.TextField(blank=True, help_text='Dónde se validó realmente. Es lo que separa un nivel TRL del siguiente y donde más se confunde la gente: un taller propio no es un entorno real.'),
        ),
    ]
