# Generated by Django 5.2.6 on 2026-07-21 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0047_faseproyecto_entorno_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorresultado',
            name='linea_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor antes de empezar el proyecto.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='indicadorresultado',
            name='meta_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='indicadorresultado',
            name='tipo',
            field=models.CharField(choices=[('numerico', 'Cantidad'), ('porcentaje', 'Porcentaje'), ('binario', 'Se logra o no se logra'), ('cualitativo', 'Descriptivo')], default='cualitativo', max_length=20),
        ),
        migrations.AddField(
            model_name='indicadorresultado',
            name='unidad',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='indicadorresultado',
            name='valor_medido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='IndicadorCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('numerico', 'Cantidad'), ('porcentaje', 'Porcentaje'), ('binario', 'Se logra o no se logra'), ('cualitativo', 'Descriptivo')], default='numerico', max_length=20)),
                ('unidad', models.CharField(blank=True, help_text='En que se expresa: ensayos, horas, personas, kg...', max_length=60)),
                ('medio_verificacion', models.CharField(blank=True, help_text='De donde sale el dato: bitacora de laboratorio, informe, planilla...', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_catalogo', to='proyectos.organizacion')),
            ],
            options={
                'verbose_name': 'indicador del catalogo',
                'verbose_name_plural': 'indicadores del catalogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='indicadorresultado',
            name='catalogo',
            field=models.ForeignKey(blank=True, help_text='Indicador del catalogo de la organizacion, si se eligio uno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos', to='proyectos.indicadorcatalogo'),
        ),
        migrations.AddConstraint(
            model_name='indicadorcatalogo',
            constraint=models.UniqueConstraint(fields=('organizacion', 'nombre'), name='indicador_unico_por_organizacion'),
        ),
    ]
