# Generated by Django 5.2.6 on 2026-07-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0049_sembrar_catalogo_de_indicadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='paso_wizard',
            field=models.PositiveSmallIntegerField(default=1, help_text='Hasta que paso de la creacion se avanzo. Sirve para retomar un borrador.'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('en_pausa', 'En pausa'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
