# Generated by Django 5.2.6 on 2026-07-22 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0053_indicador_exige_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadorcatalogo',
            name='tipo',
            field=models.CharField(choices=[('binario', 'Se logra o no se logra'), ('numerico', 'Una cantidad que hay que alcanzar'), ('porcentaje', 'Un porcentaje que hay que alcanzar'), ('cualitativo', 'Descriptivo, se evalua a criterio')], default='binario', max_length=20),
        ),
        migrations.AlterField(
            model_name='indicadorresultado',
            name='tipo',
            field=models.CharField(choices=[('binario', 'Se logra o no se logra'), ('numerico', 'Una cantidad que hay que alcanzar'), ('porcentaje', 'Un porcentaje que hay que alcanzar'), ('cualitativo', 'Descriptivo, se evalua a criterio')], default='cualitativo', max_length=20),
        ),
        migrations.CreateModel(
            name='MensajeAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.PositiveSmallIntegerField(help_text='Paso del asistente en el que se escribio el mensaje.')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente')], max_length=12)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_asistente', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'mensaje del asistente',
                'verbose_name_plural': 'mensajes del asistente',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
