# Generated by Django 5.2.6 on 2026-07-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0054_asistente_del_wizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='exige_aprobacion_trl',
            field=models.BooleanField(default=False, help_text='Si se activa, subir de nivel TRL necesita ademas el visto bueno de un responsable, apoyado en la revision de la IA. Es la tercera llave de la puerta.'),
        ),
    ]
