from django.urls import path

from . import views


urlpatterns = [
    path("control/login/", views.superadmin_login, name="superadmin_login"),
    path("control/salir/", views.superadmin_logout, name="superadmin_logout"),
    path("control/usuarios/", views.superadmin_usuarios_globales, name="superadmin_usuarios"),
    path("control/estadisticas/", views.superadmin_estadisticas, name="superadmin_estadisticas"),
    path("login/<slug:organizacion_slug>/", views.organizacion_login, name="organizacion_login"),
    path("organizacion/configuracion/", views.organizacion_configuracion, name="organizacion_configuracion"),
    path("registro/", views.registro_publico, name="registro"),
    path("registro/areas/", views.areas_por_sede_json, name="areas_por_sede"),
    path("registro/pendiente/<int:pk>/", views.registro_pendiente, name="registro_pendiente"),
    path("registro/resolver/<str:token>/", views.registro_resolver, name="registro_resolver"),
    path("registro/verificar/<int:pk>/", views.verificar_correo, name="verificar_correo"),
    path("control/organizaciones/", views.superadmin_organizaciones, name="superadmin_organizaciones"),
    path("control/organizaciones/nueva/", views.superadmin_organizacion_crear, name="superadmin_organizacion_crear"),
    path("", views.dashboard, name="dashboard"),
    path("panel/", views.panel_general, name="panel_general"),
    path("usuarios/", views.UsuarioListView.as_view(), name="usuario_lista"),
    path("usuarios/nuevo/", views.UsuarioCreateView.as_view(), name="usuario_crear"),
    path("perfil/editar/", views.perfil_editar, name="perfil_editar"),
    path("usuarios/<int:pk>/", views.usuario_detalle, name="usuario_detalle"),
    path("usuarios/<int:pk>/editar/", views.UsuarioUpdateView.as_view(), name="usuario_editar"),
    path("usuarios/<int:pk>/eliminar/", views.usuario_eliminar, name="usuario_eliminar"),
    path("chat/", views.chat_privado, name="chat_lista"),
    path("chat/<int:usuario_id>/", views.chat_privado, name="chat_privado"),
    path("chat/grupo/<int:grupo_id>/", views.chat_privado, name="chat_grupo"),
    path("chat/grupo/nuevo/", views.crear_grupo_chat, name="chat_grupo_nuevo"),
    path("notificaciones/marcar-leidas/", views.marcar_notificaciones_leidas, name="marcar_notificaciones_leidas"),
    path("proyectos/", views.ProyectoListView.as_view(), name="proyecto_lista"),
    path("inventario/", views.inventario_lista, name="inventario_lista"),
    path("inventario/nuevo/", views.inventario_crear, name="inventario_crear"),
    path("inventario/lector/", views.inventario_lector, name="inventario_lector"),
    path("inventario/buscar/", views.inventario_buscar_json, name="inventario_buscar_json"),
    path("inventario/<int:pk>/stock/", views.inventario_agregar_stock, name="inventario_agregar_stock"),
    path("inventario/<int:pk>/editar/", views.inventario_editar, name="inventario_editar"),
    path("inventario/<int:pk>/eliminar/", views.inventario_eliminar, name="inventario_eliminar"),
    path("proyectos/asistente-ia/", views.asistente_ia_proyecto, name="proyecto_asistente_ia"),
    path("proyectos/nuevo/", views.ProyectoCreateView.as_view(), name="proyecto_crear"),
    path("proyectos/<int:pk>/", views.proyecto_detalle, name="proyecto_detalle"),
    path("proyectos/<int:pk>/descargar-pdf/", views.descargar_proyecto_pdf, name="proyecto_descargar_pdf"),
    path("proyectos/<int:pk>/mesa-estado/", views.proyecto_mesa_estado, name="proyecto_mesa_estado"),
    path("proyectos/<int:pk>/ia/", views.proyecto_ia_trl, name="proyecto_ia_trl"),
    path("proyectos/<int:pk>/trabajo/", views.proyecto_trabajo, name="proyecto_trabajo"),
    path("proyectos/<int:pk>/etapas/<slug:slug>/", views.etapa_trabajo, name="etapa_trabajo"),
    path("proyectos/<int:pk>/etapas/<slug:slug>/ia/", views.analizar_etapa_ia, name="etapa_ia_analizar"),
    path("proyectos/<int:pk>/etapas/<slug:slug>/generar-tareas-ia/", views.generar_tareas_etapa_ia_view, name="etapa_generar_tareas_ia"),
    path("revisiones-ia/<int:pk>/decidir/", views.decidir_revision_ia_etapa, name="revision_ia_decidir"),
    path("proyectos/<int:pk>/editar/", views.ProyectoUpdateView.as_view(), name="proyecto_editar"),
    path("proyectos/<int:pk>/eliminar/", views.proyecto_eliminar, name="proyecto_eliminar"),
    path("fases/<int:pk>/", views.fase_detalle, name="fase_detalle"),
    path("proyectos/<int:pk>/estado/", views.actualizar_estado, name="proyecto_estado"),
    path("proyectos/<int:pk>/avances/nuevo/", views.crear_avance, name="avance_crear"),
    path("proyectos/<int:pk>/tareas/nueva/", views.crear_tarea, name="tarea_crear"),
    path("proyectos/<int:pk>/evidencias/nueva/", views.subir_evidencia, name="evidencia_crear"),
    path("tareas/<int:pk>/completar/", views.completar_tarea, name="tarea_completar"),
    path("tareas/<int:pk>/editar/", views.editar_tarea, name="tarea_editar"),
    path("tareas/<int:pk>/eliminar/", views.eliminar_tarea, name="tarea_eliminar"),
    path("proyectos/<int:pk>/observaciones/nueva/", views.crear_observacion, name="observacion_crear"),
    path("proyectos/<int:pk>/inventario/usar/", views.registrar_uso_inventario, name="inventario_usar"),
    path("proyectos/<int:pk>/indicadores/<int:indicador_id>/actualizar/", views.actualizar_indicador, name="indicador_actualizar"),
]
